import type { Metadata, Viewport } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ReduxProvider } from "@/redux/provider";
import { cn } from "@/lib/utils";
import { Toaster } from "@/components/ui/sonner";

const mainFont = localFont({
  src: "./components/iransanswebfanum.ttf",
  variable: "--main-font",
  weight: "400",
  style: "normal",
  display: "swap",
  // preload: true,
});

const boldFont = localFont({
  src: "./components/iransansbold.ttf",
  variable: "--farsi-bold-font",
  weight: "700",
  style: "bold",
  display: "swap",
  // preload: true,
});

export const viewport: Viewport = {
  themeColor: "#fff",
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
};

export const metadata: Metadata = {
  title: "رزرو غذای کارمندان",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="fa"
      data-scroll-behavior="smooth"
      dir="rtl"
      className={cn(mainFont.variable, boldFont.variable, "font-sans")}
    >
      <body>
        <ReduxProvider>
          <Toaster
            position="top-center"
            toastOptions={{
              className: "text-black",
              // unstyled: true,
              classNames: {
                loading: "bg-[#F8F8F8] border-[#F8F8F8] [&_svg]:text-[#F8F8F8]",
                error: "bg-red-400 border-red-400 [&_svg]:text-red-200",
                success: "bg-green-200 border-green-400 [&_svg]:text-green-400",
              },
            }}
          />
          {children}
        </ReduxProvider>
      </body>
    </html>
  );
}
